pipeline {
    agent any
    stages {
        stage('Build Folder Structure using IFS Config Builder') {
            steps {
                bat '''cd /d D:\\IFS_J\\Build && RMDIR /S /Q .
                cd /d C:\\Program Files (x86)\\IFS\\IFSConfigBuilder10
                IfsConfigBuilder .\\setup.ini .\\log.txt
                type log.txt'''
                echo '----------------------------Building Folder Structure step is executed----------------------------'
            }
        }
        stage('Build') {
            steps {
                bat '''cd /d D:\\Build_home\\build
                set DELIVERY=D:\\IFS_J\\Build
                build.cmd SERVER DB'''
                echo '----------------------------Build step is executed----------------------------'
            }
        }
    }
}
